package com.project.soldiapp.base_ui_tests;


import android.app.Activity;
import android.view.View;
import android.view.ViewGroup;
import android.view.ViewParent;

import androidx.test.espresso.ViewInteraction;
import androidx.test.filters.LargeTest;
import androidx.test.rule.ActivityTestRule;
import androidx.test.runner.AndroidJUnit4;

import com.project.soldiapp.MainActivity;
import com.project.soldiapp.R;
import com.project.soldiapp.data_handling.ExpenseRepository;

import org.hamcrest.Description;
import org.hamcrest.Matcher;
import org.hamcrest.TypeSafeMatcher;
import org.junit.Before;
import org.junit.Rule;
import org.junit.Test;
import org.junit.runner.RunWith;

import static androidx.test.espresso.Espresso.onView;
import static androidx.test.espresso.assertion.ViewAssertions.matches;
import static androidx.test.espresso.matcher.ViewMatchers.hasFocus;
import static androidx.test.espresso.matcher.ViewMatchers.isDisplayed;
import static androidx.test.espresso.matcher.ViewMatchers.withContentDescription;
import static androidx.test.espresso.matcher.ViewMatchers.withHint;
import static androidx.test.espresso.matcher.ViewMatchers.withId;
import static androidx.test.espresso.matcher.ViewMatchers.withResourceName;
import static androidx.test.espresso.matcher.ViewMatchers.withText;
import static org.hamcrest.Matchers.allOf;

/**
 * Some part of the code was autogenerated and other edited or created from scratch
 */
@LargeTest
@RunWith(AndroidJUnit4.class)
public class HomeFragmentTest {

    @Rule
    public ActivityTestRule<MainActivity> mActivityTestRule = new ActivityTestRule<>(MainActivity.class);

    Activity activity;

    @Before
    public void before(){
        activity=mActivityTestRule.getActivity();
    }

    @Test
    public void testTestNavDrawer() {
        ViewInteraction imageButton = onView(
                allOf(withContentDescription(activity.getString(R.string.navigation_drawer_open)),
                        isDisplayed()));
        imageButton.check(matches(isDisplayed()));
    }

    @Test
    public void testTestToolbarTitle() {
        ViewInteraction textView = onView(
                allOf(withText(activity.getString(R.string.app_name)),
                        isDisplayed()));
        textView.check(matches(withText(activity.getString(R.string.app_name))));
    }


    @Test
    public void testFragmentTitle() {
        ViewInteraction textView = onView(
                allOf(withId(R.id.addExpense), withText(activity.getString(R.string.quantity_expense_title)),
                        isDisplayed()));
        textView.check(matches(withText(activity.getString(R.string.quantity_expense_title))));

    }

    @Test
    public void testStartExpenseButton(){
        ViewInteraction imageView = onView(allOf(withId(R.id.startExpenseButton),hasFocus()));
        imageView.check(matches(isDisplayed()));
    }

    @Test
    public void testTextFieldExpense(){
        ViewInteraction editText = onView(
                allOf(withId(R.id.inputExpense), withHint("€"),
                        isDisplayed()));
        editText.check(matches(withHint("€")));

    }

    @Test
    public void testInitialAdvice() {
        ViewInteraction textView = onView(
                allOf(withId(R.id.initialAdvice), withText(activity.getString(R.string.firstTime)),
                        isDisplayed()));

    }
}
